# Generated by Django 4.2.4 on 2023-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='.', upload_to='resources/images', verbose_name='Poster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
    ]
