# Generated by Django 4.2.4 on 2023-12-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_movie_genre_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='static', verbose_name='Poster'),
        ),
    ]
