# Generated by Django 4.2.4 on 2023-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_movie_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='catalog.genre'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='static/images', verbose_name='Poster')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('genre', models.ManyToManyField(related_name='show_genre', to='catalog.genre')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
    ]
