# Generated by Django 4.2.4 on 2023-12-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_movie_date_updated_alter_movie_genre_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
