# Generated by Django 4.2.4 on 2024-01-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_show_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
    ]
