# Generated by Django 4.2.4 on 2024-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_show_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='show',
            name='synopsis',
            field=models.TextField(verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.DateField(verbose_name='Release date'),
        ),
    ]
