# Generated by Django 4.2.4 on 2024-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_movie_date_added_alter_movie_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catálogos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gênero(s)'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='no-image.jpg', upload_to='static/assets', verbose_name='Pôster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(related_name='genero_serie', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, upload_to='static/assets', verbose_name='Pôster'),
        ),
        migrations.AlterField(
            model_name='show',
            name='synopsis',
            field=models.TextField(verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
    ]
