# Generated by Django 4.2.4 on 2024-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_movie_poster_alter_movie_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Release year'),
        ),
    ]
