# Generated by Django 4.2.4 on 2024-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='assets/no-image.jpg', upload_to='static/assets', verbose_name='Cartaz'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(default='no-image.jpg', upload_to='static/assets', verbose_name='Cartaz'),
        ),
    ]
