# Generated by Django 4.2.4 on 2024-02-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='catalog/no-image.jpg', upload_to='catalog', verbose_name='Cartaz'),
        ),
    ]
