# Generated by Django 4.2.4 on 2024-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ano de lançamento'),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ano de lançamento'),
        ),
    ]
